{% set name = "model-index" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2f9870200f3b00813881b07b90d2c67291663534e43915c75fe476b6977bf2ad
    patches:
      - 0001-write-deps-from-missing-file.patch
  - url: https://raw.githubusercontent.com/paperswithcode/model-index/main/LICENSE
    sha256: addec7ad58188c4d6df6f578fb0c6877bd799d787ecbd9f133213de995b345a4
  - git_url: https://github.com/paperswithcode/model-index
    git_rev: 09c7865ab2cbe00827d3af879a2faf7d286cb1b7
    folder: github_repo

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  entry_points:
    - mi = modelindex.__main__:cli

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
    - git  # [not win]
  host:
    - python
    - pip
    - pyyaml
    - markdown
    - ordered-set
    - click
    - wheel
    - setuptools
  run:
    - python
    - pyyaml
    - markdown
    - ordered-set
    - click

test:
  source_files:
    - github_repo/tests
  imports:
    - modelindex
  commands:
    - pip check
    # skipping one test because of missing test file
    - cd github_repo
    - pytest -k "not test_examples" tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/paperswithcode/model-index
  summary: Create a source of truth for ML model results and browse it on Papers with Code
  description: |
    model-index has two goals:
      * Make it easy to maintain a source-of-truth index of Machine Learning model metadata
      * Enable the community browse this model metadata on Papers with Code
    The main design principle of model-index is flexibility. You can store your model metadata however is the most
    convenient for you - as JSONs, YAMLs or as annotations inside markdown. model-index provides a convenient way to
    collect all this metadata into a single file that's browsable, searchable and comparable.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/paperswithcode/model-index
  dev_url: https://github.com/paperswithcode/model-index

extra:
  recipe-maintainers:
    - giswqs
