{% set name = "model-index" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/model-index-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  entry_points:
    - mi = modelindex.__main__:cli

requirements:
  host:
    - python
    - pip
    - pyyaml
    - markdown
    - ordered-set
    - click
  run:
    - python
    - pyyaml
    - markdown
    - ordered-set
    - click

test:
  source_files:
    - tests
  imports:
    - modelindex
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/paperswithcode/model-index
  summary: Create a source of truth for ML model results and browse it on Papers with Code
  description: |
    model-index has two goals:
      * Make it easy to maintain a source-of-truth index of Machine Learning model metadata
      * Enable the community browse this model metadata on Papers with Code
    The main design principle of model-index is flexibility. You can store your model metadata however is the most
    convenient for you - as JSONs, YAMLs or as annotations inside markdown. model-index provides a convenient way to
    collect all this metadata into a single file that's browsable, searchable and comparable.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/paperswithcode/model-index
  dev_url: https://github.com/paperswithcode/model-index

extra:
  recipe-maintainers:
    - giswqs
